platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'SlideImageScrollView' do
  
  pod 'Kingfisher', '~> 3.2.1'

  target 'SlideImageScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlideImageScrollViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
